global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'agentzero-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Service metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Agent metrics
  - job_name: 'agents'
    static_configs:
      - targets:
          - 'planning-agent:8080'
          - 'execution-agent:8080'
          - 'research-agent:8080'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Dashboard metrics
  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:80']
    metrics_path: '/metrics'
    scrape_interval: 30s